noremap <leader>1 :b1 <CR>
noremap <leader>2 :b2 <CR>
noremap <leader>3 :b3 <CR>
noremap <leader>4 :b4 <CR>
noremap <leader>5 :b5 <CR>
noremap <leader>6 :b6 <CR>
noremap <leader>7 :b7 <CR>
noremap <leader>8 :b8 <CR>
noremap <leader>9 :b9 <CR>
